### ISSUE TITLE
Still not working in Sketch 68.2

### ISSUE THREAD

**Issue by ColinLondon** [aparajita/sketch-style-master#21] opened 2020-09-03 00:25 UTC
Is this dead? If so, pity. Cheers.

**Comment by symdesign** [comment] 2020-09-10 14:09
Following message can be found on Sketch's plugin log `~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log` 
```
TypeError: context.api is not a function. (In 'context.api()', 'context.api' is null)
    at SharedStyleRenamer (/Users/friedrichschultheiss/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Style Master.sketchplugin/Contents/Sketch/plugin.js:186:30)
```

A auick and dirty fix would be:
- Sketch → Plugins → Style Master (Right Click) → Reveal in Finder 
- Open `Style Master.sketchplugin` with [VS Code](https://code.visualstudio.com/) to see the contained files
- Open `plugin.js`
- On line 186: Replace `this.sketch = context.api();` with `this.sketch = require('sketch');`
- Save 🧙‍♂️

**Comment by aparajita** [comment] 2020-09-11 00:02
Duplicate of #15

**Comment by aparajita** [comment] 2020-09-11 00:03
It's more complicated than just changing that one line.

**Closed by aparajita** 2020-09-11 00:02 UTC

**Comment by symdesign** [comment] 2020-09-11 06:01
Of course, it is more complicated. That is why I called it "quick and dirty". And it works :)

**Comment by ColinLondon** [comment] 2020-09-11 10:48
Yep. Worked! Bravo.

**Comment by aparajita** [comment] 2020-09-11 15:51
I could have sworn there were other things breaking as well. I'll give it a shot, thanks!

**Comment by aparajita** [comment] 2020-09-14 00:18
v1.0.5 works, thanks @symdesign for the help. There were some other changes I had to make to get it to build, but everything seems to work now.

**Comment by ColinLondon** [comment] 2020-09-14 00:27
Sure does. Brilliant plugin.
Unfortunately, the workaround and new version came just after I manually renamed 840 styles in a doc!
;-)
