### ISSUE TITLE
Not working in Sketch 61.1

### ISSUE THREAD

**Issue by davidmcneroe86** [aparajita/sketch-style-master#16] opened 2020-05-25 18:39 UTC
When I try open plugin it doesn't launch in Sketch 61.1

So, Plugins > Style Master > Rename Text Styles....and the window doesn't open

Thanks

**Comment by staffdefer** [comment] 2020-05-29 08:30
Same for me. Please fix, I love this plugin <3.

**Comment by aparajita** [comment] 2020-08-19 23:17
Duplicate of #15

**Closed by aparajita** 2020-08-19 23:17 UTC

**Comment by aparajita** [comment] 2020-09-14 00:24
v1.0.5 works with Sketch 66+, but no longer with older versions. Sketch 61 is ancient, sorry, I can't support everything.

**Comment by davidmcneroe86** [comment] 2020-09-14 08:53
Thanks, seems to work now with the update!
