### ISSUE TITLE
current sketch 67.2 doesn't work

### ISSUE THREAD

**Issue by wuwa** [aparajita/sketch-style-master#18] opened 2020-07-21 17:47 UTC
please please can we use it again?

**Comment by aparajita** [comment] 2020-07-23 06:11
I'd love to update it, but I have too many other time commitments right now.

**Comment by aparajita** [comment] 2020-08-19 23:17
Duplicate of #15

**Closed by aparajita** 2020-08-19 23:17 UTC

**Comment by aparajita** [comment] 2020-09-14 00:22
v1.0.5 works, thanks to @symdesign for the help.
